name: GitHub Actions Demo
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      
  pull_request:
    branches:
      - 'main'

  schedule:
      - cron: '15 6 * * 0'

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output event name and repo
      - run: |
           echo "The job was triggered by event {{ github.event_name }}"
           echo "The branch is {{ github.branch }} and the repository is {{ github.repository }}"

      - uses: actions/checkout@v4
      
      - name: List files in the repository
      - run:
          echo "The files under the repository {{ github.repository }}"
          tree
    
      
